Infotecs.Intern.RssReader/Models/RssFeed.cs
using System;

namespace Infotecs.Intern.RssReader.Models
{
    /// <summary>
    /// Модель Rss новости.
    /// </summary>
    public class RssFeed
    {
        /// <summary>
        /// Категория.
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        /// Описание.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Директива.
        /// </summary>
        public string Guid { get; set; }

        /// <summary>
        /// Ссылка.
        /// </summary>
        public string Link { get; set; }

        /// <summary>
        /// Дата публикации.
        /// </summary>
        public DateTime PubDate { get; set; }

        /// <summary>
        /// Заголовок.
        /// </summary>
        public string Title { get; set; }
    }
}

Infotecs.Intern.RssReader/Models/RssReaderOptions.cs
using System;
using System.Collections.Generic;

namespace Infotecs.Intern.RssReader.Models
{
    /// <summary>
    /// Модель параметров.
    /// </summary>
    public class RssReaderOptions
    {
        /// <summary>
        /// Коллекция Rss ссылок.
        /// </summary>
        public List<string> Feeds { get; set; }
        /// <summary>
        /// Интервал обновления.
        /// </summary>
        public TimeSpan UpdateInterval { get; set; }
        /// <summary>
        /// Включить форматирование.
        /// </summary>
        public bool EnableFormatting { get; set; }
        /// <summary>
        /// Включить прокси.
        /// </summary>
        public bool UseProxy { get; set; }
        /// <summary>
        /// Хост.
        /// </summary>
        public string ProxyHost { get; set; }
        /// <summary>
        /// Порт.
        /// </summary>
        public int ProxyPort { get; set; }
    }
}

Infotecs.Intern.RssReader/Controllers/FeedsController.cs
using System;
using System.Threading.Tasks;
using Infotecs.Intern.RssReader.Models;
using Infotecs.Intern.RssReader.Services;
using Microsoft.AspNetCore.Mvc;

namespace Infotecs.Intern.RssReader.Controllers
{
    /// <inheritdoc/>
    public class FeedsController : Controller
    {
        private readonly ISettingsService settingsService;
        private readonly IRssService rssService;

        /// <summary>
        /// Конструктор.
        /// </summary>
        /// <param name="rssService">Логика.</param>
        /// <param name="settingsService">Поставщик конфигураций.</param>
        public FeedsController(IRssService rssService, ISettingsService settingsService)
        {
            this.rssService = rssService;
            this.settingsService = settingsService;
        }

        /// <summary>
        /// Индекс контроллер.
        /// </summary>
        /// <returns>View.</returns>
        public async Task<IActionResult> Index()
        {
            ViewBag.listItems = await rssService.GetRssFeedsAsync();
            ViewBag.updateInterval = settingsService.GetSettings().UpdateInterval.TotalSeconds;
            ViewBag.enableFormatting = settingsService.GetSettings().EnableFormatting;

            return View();
        }
    }
}

Infotecs.Intern.RssReader/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using Infotecs.Intern.RssReader.Models;
using Infotecs.Intern.RssReader.Services;
using Microsoft.AspNetCore.Mvc;

namespace Infotecs.Intern.RssReader.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ISettingsService settingsService;

        /// <summary>
        /// Конструктор.
        /// </summary>
        /// <param name="settingsService">Поставщик настроек.</param>
        public SettingsController(ISettingsService settingsService)
        {
            this.settingsService = settingsService;
        }

        /// <summary>
        /// HttpGet для настроек.
        /// </summary>
        /// <returns>View.</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View(settingsService.GetSettings());
        }

        /// <summary>
        /// HttpPost для настроек.
        /// </summary>
        /// <param name="answeredOptions">Измененные настройки.</param>
        /// <param name="feeds">Измененная строка ссылок.</param>
        /// <returns>Redirect на главную.</returns>
        [HttpPost]
        public ActionResult Index(RssReaderOptions answeredOptions, string feeds)
        {
            answeredOptions.Feeds = new List<string>(feeds.Split("\n"));

            if (settingsService.GetSettings() != answeredOptions)
            {
                if (ValidateOptions(answeredOptions))
                {
                    settingsService.SaveSettings(answeredOptions);
                }
                else
                {
                    ModelState.AddModelError("", "Неверный параметр.");
                }
            }

            return Redirect("/");
        }

        private bool ValidateOptions(RssReaderOptions options)
        {
            if (options.EnableFormatting.Equals(null) ||
                options.UpdateInterval.Equals(null) ||
                options.UseProxy.Equals(null))
            {
                return false;
            }

            foreach (var item in options.Feeds)
            {
                if (!Uri.TryCreate(item, UriKind.Absolute, out var a))
                {
                    return false;
                }
            }
            return true;
        }
    }
}

Infotecs.Intern.RssReader/Views/Feeds/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<meta http-equiv="refresh" content="@ViewBag.updateInterval">

@model Infotecs.Intern.RssReader.Models.RssFeed

@foreach (var item in ViewBag.listItems)
{
    <div>
        <details class="sum_border">
            <summary>
                <a href="@item.Link">@item.Title</a>
            </summary>

            <p>
                @if (ViewBag.enableFormatting)
                {
                    @Html.Raw(@item.Description)
                }
                else
                {
                    @item.Description
                }
            </p>
            <p>
                @item.Category -
                @if (item.PubDate.Date == DateTime.Today)
                {
                    @item.PubDate.ToString("hh:mm")
                }
                else
                {
                    @item.PubDate.ToString("dd.MM.yyyy hh:mm")
                }
            </p>
        </details>
    </div>
    <br>
}

Infotecs.Intern.RssReader/Views/Settings/Index.cshtml
@using System
@model RssReaderOptions
@{
    ViewData["Title"] = "Settings";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
<div>
    @Html.TextBoxFor(b => b.UpdateInterval, new { @class = "form-control", placeholder = "Update Interval" })

    <br />
    @Html.CheckBoxFor(b => b.EnableFormatting)
    @Html.LabelFor(b => b.EnableFormatting)
    @Html.ValidationMessageFor(b => b.EnableFormatting)
    <br />

    @{
        var feeds = string.Join("\n", Model.Feeds);
    }

    @Html.TextAreaFor(b => feeds, new { @class = "form-control", placeholder = "Sources of RSS", rows = 5})
</div>
    <br/>
    <button class="btn btn-success" type="submit">Save</button>
}

Infotecs.Intern.RssReader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Infotecs.Intern.RssReader</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Feeds" asp-action="Index" class="navbar-brand">RSSReader</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Settings" asp-action="Index">Settings</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Infotecs.Intern.RSSReader</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>